### ISSUE TITLE
[US] As a User, I can create a Schema

### ISSUE THREAD

**Issue by arthur-remy** [Consensys/linea-attestation-registry#14]
As a User, I want to create a schema so that I can use it later to describe the data inside the attestation I will be issuing.

## Requirements
* Anyone can create a schema. No rule to prevent anyone from creating a schema
* Schema are created through the `Schema Registry` smart contract
* To create a schema, the user should pass metadata (see table below) except the id
* When creating a schema, we should check that the id doesn't already exists and the `name` and `schema` string field should not be empty
* Schema creation should trigger an event
* Schemas should be stored in a mapping (id -> struct with metadata except id) within the `Schema Registry`

## Todo
- [ ] Remove examples files from Foundry (see in `/tests`, `/contracts` and `/scripts`)
- [ ] In a folder `/contracts/struct` create a smart contract whose single purpose is to have a struct `Schema`, as per the description hereunder (except that `id`MUST NOT be in the struct)
- [ ] In the folder `/contracts`, create an empty smart contract `SchemaRegistry`, transparentUpgradable
- [ ] In this smart contract, create a mapping `Schemas` bytes32 => struct Schema, public
- [ ] In this smart contract, create a public view `getIdFromSchemaString(string schema) returns bytes32`, that just do the keccack of the string schema inputed
- [ ] In this smart contract, create a method `createSchema(string name, string description, string context, string schemaString)`
- [ ] Check if the getIdFromSchemaString(schemaString) already exists in the `schemas`mapping. Revert with custom error if already exists
- [ ] Create the struct Schema and store it in the mapping `schemas`
- [ ] Trigger an event `schemaCreated(string name, bytes32 schemaId)
- [ ] Add the deployment script and explain in the readme how to trigger it

## Acceptance criteria
* Should include a script to deploy `Schema Registry`
* Should include 100% unit-tests (including accessing the schema metadata through the mapping)

### Additional information

| Workload estimate | 
|--------|
| TBD |

#### Schema metadata
Field | Type | Description | Mandatory?
-- | -- | -- | --
id | uint256 | The unique id of this schema, keccack256 of “schema” field | Computed
context | string (URI) | A link to some URL that gives context to the fields in the schema, can be something like “https://schema.org/Person” | Optional
name | string | A descriptive name for the schema | Mandatory
description | string (URI) | Link to documentation about the schema, it’s intended use etc. | Optional
schema | string | A string containing the fields and properties for the schema. | Mandatory
