### ISSUE TITLE
[US] As a User, I can discover all the Schemas

### ISSUE THREAD

**Issue by arthur-remy** [Consensys/linea-attestation-registry#15]
As a user, I want to access the list of all available Schemas so that I can find them without knowing their IDs

## Requirements
* When a `Schema` is created, we should store its ID in an array
* We should provide a function to get the length of this array

## Todo
- [x] Create an array `public bytes32[] schemaIds`
- [x] In the `SchemaRegistry` contract, when a Schema is added in the schemas mapping, push its ID in the `schemaIds` array
- [x] Add a getter to get `schemaIds` array length

## Acceptance criteria
* Should include 100% unit-tests (including accessing schemas ID with an index in the array)  

### Additional information

| Workload estimate | 
|--------|
| TBD |
