### ISSUE TITLE
[US] As a Dev, I have a repository with Foundry and CI up and running

### ISSUE THREAD

**Issue by fdemiramon** [Consensys/linea-attestation-registry#17]
## Requirements
Install Foundry and setup a CI
eg: awesome-repo to have a look: https://github.com/sablier-labs/v2-core. Please also have a deep look on their tests folder.

## Todo
- [x] Create a branch `dev` forked from `main` (main will remain empty till the first mainnet deployment)
- [x] Create a branch for this issue, following the WoW described in the issue #10 - Ways of Working. Note that PR to be created for all the tasks including this one, will point the `dev`branch, as described in the WoW
- [x] Install Foundry, keeping the example smart contract and test available in the boilerplate
- [x] Find the best way to have a linter available through Foundry, the IDE and in the CI
- [x] In the readme, 1. describe how to install Foundry, and 2. describe the following key methods: h2 launch tests, h2 deploy on Anvil
- [x] Prepare the CI, to have it running for all PRs created and merged, for any branches, doing 1. forge build and 2. forge test

## Acceptance Criteria
- [x] have a repository with Foundry installed, a CI up and running and a basic documentation on how to use Foundry
