### ISSUE TITLE
[SPIKE] As a Verax Dev, I want to know if we could consider to parse Schemas on-chain

### ISSUE THREAD

**Issue by fdemiramon** [Consensys/linea-attestation-registry#18]
## Requirements
This is a not in the list of Business Requirements, but we may want at some point to parse Schemason-chain to ensure data consistency.
This spike should investigate on the possible technical implementations and gas consumption impacts.
The outcome may be:
* no go: not possible at all
* go, view only: not possible through a write transaction (create Schema and create Attestation), but possible with a view, in order the user can do a preflight of what he plan to post
* go: this is possible and gas consumption impact is a soft o of transaction gas consumption

## Todo
- [ ] Identify libraries to parse string
- [ ] Using fixtures, calculate the gas consumption to parse and check payload
- [ ] Describe in this GH issue the outcomes 

## Example of steps to parse and validate a schema
* get the schemaString
* explode it (comma separated)
* recursively get child schemas
* check that each chunk is
  * a type, among a list of predefined types
  * a space (between the type and the field name)
  * a field name

**Comment by alainncls** [comment]
Won't do
