### ISSUE TITLE
[US] As a Module Developer, I can publish my Module

### ISSUE THREAD

**Issue by arthur-remy** [Consensys/linea-attestation-registry#20]
As a module creator, I want to publish my modules on the Module Registry so that they can be used in Portals

## Requirements
* Anyone can create a Module. No rule to prevent anyone from creating a Module
* Modules are registered through the `Module Registry` smart contract
* Modules are identified via their Smart Contract addresses
* Modules published should be stored in an array (for discoverability)
* Modules' metadata should be stored in a mapping when the module is published
    * The module smart contract address is used as a key
    * Module name and description (optional) are stored inside the mapping (struct)
* Publishing a module should trigger an event

## Todo
- [ ] Create a `ModuleRegistry` contract
- [ ] Create a `Module` struct to store a Module metadata
- [ ] Add a mapping to store modules (`address => Module`)
- [ ] Add an array to store modules
- [ ] Add a `register()` function to add a new Module to the mapping and the array
- [ ] To register a Module, it must have a name and an address, throw custom errors if not
- [ ] When a Module is registered, emit a custom `ModuleRegistered` event

- [ ] Add a `ModuleRegistry` script to be able to deploy it easily + a pnpm command to trigger it
- [ ] Add a `ModuleRegistry` set of unit tests to cover the happy path + the errors and events triggering

## Acceptance criteria
* Should include a script to deploy the `Module Registry`
* Should include 100% unit-tests (including accessing the metadata through the mapping)

## Additional information
| Workload estimate | 
|--------|
| TBD |
