### ISSUE TITLE
[US] As an Attestation Issuer, I want to revoke an Attestation I issued

### ISSUE THREAD

**Issue by orbmis** [Consensys/linea-attestation-registry#31]
As an Attestation Issuer,
I want to be able to override an attestation that I issued,
So that consumers know when they are using up to date information

## Requirements
 * The Portal that issues Attestations must specify which attestations are revocable.
 * This can be done by maintaining a mapping of Schema IDs to revocable flags, i.e.: `mapping(bytes32 => bool) public revocableSchemas`;
 * The ability to revoke Attestations can only be done by the Portal owner

## Todo

- [ ] In the `Portal` struct, add an `revocableSchemas` mapping
- [ ] In the `Attestation` struct, add 2 fields:
    - [ ] `revoked` (bool), false by default and true when the Attestation is overridden
    - [ ] `replacedBy` (bytes32), empty by default and set to an `Attestation` ID overriding the current `Attestation`    
    - [ ] `revocationDate ` (uint64), 0 by default and with the block timestamp of the override action
- [ ] In the `PortalRegistry`, add a `revoke` method that:
    - [ ] Checks that the caller is the owner of the targeted `Portal`
    - [ ] Checks that the targeted `Attestation`'s `Schema` authorizes the override action
    - [ ] Issues a new attestation with the given params
    - [ ] Updates the original `Attestation` fields (`revoked`, `replacedBy` and `replaceDate`)
    - [ ] Emits a dedicated `ReplacedAttestation` event

## Acceptance criteria

**Given** I have already issued an Attestation
And the Attestation has been issued using a Portal that allows revoke for the Schema I used
**When** I submit an revoke transaction specifying the Attestation ID
And I have issued the transaction from an address that is listed as owner in the Portal
**Then** that Attestation will have it's `revoked` property set to `true`

**Comment by orbmis** [comment]
iirc, Eugene suggested that we should also “replace” revoked attestations in 100% of the cases.  This point needs clarification I think ,but otherwise I think this approach makes sense

**Comment by orbmis** [comment]
`replacedBy (bytes32)` → should be `replacedBy (uint256)` as we agreed yesterday that attestation ids would be auto-increment
