### ISSUE TITLE
[US] As a Module Developer, I want to have an abstract Module smart contract

### ISSUE THREAD

**Issue by alainncls** [Consensys/linea-attestation-registry#40]
As a Module Developer,
I want to have an abstract Module smart contract,
so that it's easier to follow a common format

## Requirements
* Provide an abstract `Module` smart contract to help Module Developers create their own compatible Module
* The contract has a `run` function, which doesn't change the input parameters
* The run function returns the input parameters as is

## Todo
- [ ] Create an `abstract contract Module` following Solidity's definition of an [abstract contract
](https://docs.soliditylang.org/en/latest/contracts.html#abstract-contracts)
- [ ] This contract has a `run(bytes memory attestationPayload, bytes memory validationPayload, bytes32 schemaId, address msgSender)` function, return the same 4 parameters unchanged
- [ ] This contract is stored in `src/interface`

## Acceptance criteria
* There is an abstract `Module` contract in `src/interface`
* The contract has a `run` function

### Additional information

| Workload estimate |
|--------|
| TBD |

**Comment by satyajeetkolhapure** [comment]
As discussed in the call, I have made changes to AbstractModule run method return type to only return attestation and validation payload, as schemaId and msgSender will not be changed in run method. Also used AbstractModule name to avoid confusion with struct Module.
