### ISSUE TITLE
[US] As a Module Developer, I want to have an example Module I can refer to, that implements check of MsgSender

### ISSUE THREAD

**Issue by alainncls** [Consensys/linea-attestation-registry#43]
As a Module Developer,
I want to have an example Module smart contract as a reference,
so that it's easier to create my own Module

## Requirements
* Provide a "MsgSender" `Module` smart contract, following the abstract Module created in #40 
* It is able to tell if the `msg.sender` is an hardcoded address it stores

## Todo
- [ ] Create a `contract MsgSenderModule` following the abstract `Module` contract
- [ ] This contract has an `expectedMsgSender` field with a hardcoded address
- [ ] The `run` function is able to say if the initial caller is equal to this address

## Acceptance criteria
* There is a "MsgSenderModule" contract in `src/examples/module`
* The contract implements the Module interface via EIP-165
* The `run` function tells if the initial caller is the expected address

### Additional information

| Workload estimate |
|--------|
| TBD |
