### ISSUE TITLE
[US] As a Portal Creator, I can publish my Portal SC

### ISSUE THREAD

**Issue by fdemiramon** [Consensys/linea-attestation-registry#60]
As a Portal, I want to publish my Portal on the Portal Registry so that they can be used by Attestation Issuers
More details on this specification in the issue #7 

## Requirements
* Anyone can create a Portal as this is a SC. No rule to prevent anyone from creating a Portal
* Portals are registered through the `PortalRegistry` smart contract
* Portals are identified via their Smart Contract addresses (i.e portalId = portal SC address)
* Portals published should be stored in an array (for discoverability)
* Portals' metadata should be stored in a mapping when the module is published
    * The Portal smart contract address is used as a key
    * Portal name and description are stored inside the mapping (struct)
* Publishing a Portal should trigger an event

## Todo
- [ ] Create an TransparentUpgradeable `PortalRegistry` contract
- [ ] Create a `Portal` struct to store a Portal metadata: `address id, string name, string description`
- [ ] Add a mapping to store Portals (`address => Portal`)
- [ ] Add an array to store modules
- [ ] Add a `register(address, string, description)` function to add a new Portal to the mapping and the array
- [ ] To register a Portal, it must have a name and an address non empty, throw custom errors if not
- [ ] Throw custom error on duplicate
- [ ] When a Portal is registered, emit a custom `PortalRegistered` event
- [ ] Add a `PortalRegistry` script to be able to deploy it easily + a pnpm command to trigger it
- [ ] Add a `PortalRegistry` set of unit tests to cover the happy path + the errors and events triggering

## Acceptance criteria
* Should include a script to deploy the `PortalRegistry`
* Should include 100% unit-tests (including accessing the metadata through the mapping)

## Additional information
| Workload estimate | 
|--------|
| TBD |
