### ISSUE TITLE
[US] As a Portal SC, I can create an Attestation on the AttestationRegistry

### ISSUE THREAD

**Issue by fdemiramon** [Consensys/linea-attestation-registry#61]
As a Portal, I can anchor on chain an Attestation. Only registered Portals can anchor an Attestation on-chain
More details on this specification in the issue #7 

## Requirements
* Only registered Portals can create Attestations
* Attestations are created through the `Attestation Registry` smart contract
* Attestations are identified via their keccack(portalId, nonce), where the nonce is the number of attestations already created with this Portal, minus 1. (The third Attestation created with the Portal `0xabc...ef` will have the id keccack(abi.encodePacked(`0xabc...ef`, 1)
* Attestations should be found:
           * by index, for a specific Portal
           * directly by their id
* Creating an Attestation should trigger an event

## Todo
- [ ] Create a `AttestationRegistry` contract
- [ ] Create a `Attestation` struct to store a Attestation data
- [ ] Add a mapping to store Attestations per Portal, per index (portalAddress => AttestationIndex => struct Attestation)
- [ ] Add a mapping to store Attestations per Id (AttestationId => tuple(portalAddress, AttestationIndex))
- [ ] Add an mapping of uint256 to get the number of Attestations per portalAddress
- [ ] Add a getter to get the length of an array of Attestations for a Portal
- [ ] Add a `attest(bytes32 schemaId, bytes attestationData)` function to add a new Attestation to the mapping and the array. This create method is only callable by a Portal registered. Add also the call to this method in the DefaultPortal
- [ ] Add a `revoke(bytes32 attestationId)` function to add a new Attestation to the mapping and the array. This create method is only callable by a Portal registered. Add also the call to this method in the DefaultPortal
- [ ] To create an Attestation, it must have `bytes data` and `bytes32 schemaId`
- [ ] When an Attestation is created, 1/ add it to the attestationsPerPortal 2/ add its portal and index in the list , 2/ add it to the 3/ emit a custom `AttestationCreated` event
- [ ] Add a `AttestationRegistry` script to be able to deploy it easily + a pnpm command to trigger it
- [ ] Add a `AttestationRegistry` set of unit tests to cover the happy path + the errors and events triggering

## Naive implementation of the AttestationRegistry
```

contract AttestationRegistry()

{

	public mapping (address => uint256) attestationsLengthPerPortal;
	public mapping (address => Attestation[]) attestationsPerPortal;
	public mapping (bytes32 => uint256) attestations;
	

	modifier onlyPortals()
	{
		// @dev: Test that the portalRegistry knows this Portal
		if (bytes(portalRegistry.portals(msg.sender)) == '0x')
		{
			revert AttestationCreatorNotAPortal(msg.sender);
		}
		_;
	}
	

	function attest(bytes32 schemaId, bytes attestationData) onlyPortals()
	{

		bytes32 attestationId = keccack(abi.encodePacked(msg.sender, attestationsLengthPerPortal[msg.sender]));

		Attestation attestation = Attestation(
			schemaId: schemaId,
			attestationData: attestationData,
			isRevoked: false,
			createdAt: block.timestamp
			attestationId: attestationId
		)

		attestationsPerPortal.push(attestation);
		attestations[attestationId] = attestation;
		attestationsLengthPerPortal[msg.sender]++;
                emit AttestationCreated(schemaId, msg.sender, attestationId, attestationData)
	}


}


```

## Acceptance criteria
* Should include a script to deploy the `Attestation Registry`
* Should include 100% unit-tests (including accessing the metadata through the mapping)

## Additional information
| Workload estimate | 
|--------|
| TBD |

**Comment by arthur-remy** [comment]
This one probably makes #39 redundant, right?
