### ISSUE TITLE
[US] As an Attestation Issuer, I can use the DefaultPortal of Verax as my Portal

### ISSUE THREAD

**Issue by fdemiramon** [Consensys/linea-attestation-registry#63]
This ticket is two fold:

_More details on this specification in the issue #7_ 

## Requirements
1/ Create the `DefaultPortal` smart contract
2/ Create the method on the `PortalRegistry` to deploy a clone of it

## Todo - 1/ Create the `DefaultPortal` smart contract
- [ ] Create a `DefaultPortal` contract in the /portal folder
- [ ] Create the state `address[] public modules`
- [ ] Create the state `bool public isInitialized`
- [ ] Create the method `initialize(address[] modules)`. This method will:
             - Check against the ModuleRegistry that each module mentioned is registered (otherwise revert with custom error)
             - Store modules
             Note: how to get the `moduleRegistryAddress`: one can be done assuming that the `PortalRegistry` exposes this address with a public getter. As the `PortalRegistry` will be the `msg.sender` of the initialize method, this `DefaultPortal` SC can use the `IPortalRegistry(msg.sender)` to get the addresses
- [ ] Create the method `attest(bytes attestationPayload, bytes verificationPayload)`. This method will:
             - run all the modules `IModuleRegistry.runModules(address[] modules, bytes attestationPayload, bytes verificationPayload)`. The method `runModules` does not exist on the `ModuleRegistry` and must be created in this ticket
             - Emit custom event
             - Store the attestation on the `AttestationRegistry` (not to be done in this ticket. Will be done through the ticket for attestationRegistry creation #61)
- [ ] (Out of scope) Create the method `revoke(bytes32 attestationId, bytes attestationPayload, bytes verificationPayload)`. As a basis in this DefaultPortal, the revoke functional path will be identical to the attest. Except that verification on the existence of the attestationId for this Portal have to be coded
==> Will we done via #31 

## Todo - 2/ Create the method on the `PortalRegistry` to deploy a clone of it
- [ ] On the `PortalRegistry`, create a method `deployDefaultPortal(address[] modules)` that will deploy a new `DefaultPortal` smart contract, initialize it and finally register it

## Acceptance criteria
* Should include a script to deploy the `DefaultPortal` conjointly with the `PortalRegistry`
* Should include 100% unit-tests (including accessing the metadata through the mapping)

## Additional information
| Workload estimate | 
|--------|
| TBD |

**Comment by 0xEillo** [comment]
Do we not need to define an AbstractPortal first, the DefaultPortal would then be the most basic implementation of this AbstractPortal

**Comment by alainncls** [comment]
The `revoke` method is now out of scope and will be covered by #31.
