### ISSUE TITLE
[US] As a user, I want to have a multichain Explorer, regardless of the networks where Verax is deployed

### ISSUE THREAD

**Issue by alainncls** [Consensys/linea-attestation-registry#763]
## Current behaviour

Today, the Explorer can only display data for one given network at a time.
Technically speaking, the SDK is instantiated to target one single network, and the URLs when navigating contain the network's name.

## Tasks to cover

- [ ] Upgrade to SDK V3 ("Multichain mode")
- [ ] Instantiate the SDK in only 2 modes ("Testnet" to get all testnet data, "Mainnet" to get all mainnet data)
- [ ] Stop considering the network name when reading the URLs path
- [ ] Remove the network name when creating the URLs
- [ ] Remove the networks dropdown selector from the header navbar
- [ ] Add a toggle selector in the header navbar to switch between testnets and mainnets
- [ ] Mainnets are selected by default

**Comment by Chirag-S-Kotian** [comment]
can i try this?

**Comment by alainncls** [comment]
> can i try this?

Yes you can!
Make sure you start from the `feat/multichain` branch instead of the usual ˋdev` branch 😉

**Comment by Chirag-S-Kotian** [comment]
so i have to fork feat/multichain branch right? for this issue?

**Comment by alainncls** [comment]
> so i have to fork feat/multichain branch right? for this issue?

Yes, this is the branch with the preview version of the SDK, supporting the multichain calls.
