### ISSUE TITLE
[TASK] Fix Attestation ID generation in examples

### ISSUE THREAD

**Issue by alainncls** [Consensys/linea-attestation-registry#787]
We have 2 places where an Attestation ID is not generated the right way, omitting the chain prefix:
- [EASPortal.sol:L75-L85](https://github.com/Consensys/linea-attestation-registry/blob/5863e8848e4e2d70003e74d84cf17ca07cfd90f3/contracts/src/examples/portals/EASPortal.sol#L75)
- [IndexerModuleV2.sol:L193-L208](https://github.com/Consensys/linea-attestation-registry/blob/5863e8848e4e2d70003e74d84cf17ca07cfd90f3/contracts/src/stdlib/IndexerModuleV2.sol#L196)

## Tasks

- [ ] Add a function to `AttestationRegistry` that directly returns the next attestation ID (including the chain prefix)
- [ ] Call it from the `EASPortal`
- [ ] Call it from the `IndexerModuleV2`
