### ISSUE TITLE
[TASK] Stop supporting unused arrays in Registries

### ISSUE THREAD

**Issue by alainncls** [Consensys/linea-attestation-registry#788]
3 of our Registries have arrays to keep track of the number of items they registered.
While this can be useful to easily get the number of items they registered, this data can easily be accessed off chain via the subgraph.
Also, this can lead to "Gas-Griefing Vulnerability" in some cases.

## Tasks

While we can't just delete the variable itself (the Registries being Upgradeable), we should keep the variables but stop using them (pushing into the arrays, reading from the arrays, deleting from the array, etc.)

- [ ] Stop supporting the `moduleAddresses` array in the [ModuleRegistry](https://github.com/Consensys/linea-attestation-registry/blob/5863e8848e4e2d70003e74d84cf17ca07cfd90f3/contracts/src/ModuleRegistry.sol#L25)
- [ ] Stop supporting the `portalAddresses` array in the [PortalRegistry](https://github.com/Consensys/linea-attestation-registry/blob/5863e8848e4e2d70003e74d84cf17ca07cfd90f3/contracts/src/PortalRegistry.sol#L26)
- [ ] Stop supporting the `schemaIds` array in the [SchemaRegistry](https://github.com/Consensys/linea-attestation-registry/blob/5863e8848e4e2d70003e74d84cf17ca07cfd90f3/contracts/src/SchemaRegistry.sol#L20C20-L20C29)
- [ ] Change the `getModulesNumber` [function of the SDK](https://github.com/Consensys/linea-attestation-registry/blob/5863e8848e4e2d70003e74d84cf17ca07cfd90f3/sdk/src/dataMapper/UtilsDataMapper.ts#L18) to rely on the subgraph instead of the contract
- [ ] Change the `getPortalsCount` [function of the SDK](https://github.com/Consensys/linea-attestation-registry/blob/5863e8848e4e2d70003e74d84cf17ca07cfd90f3/sdk/src/dataMapper/UtilsDataMapper.ts#L26) to rely on the subgraph instead of the contract
- [ ] Change the `getSchemasNumber` [function of the SDK](https://github.com/Consensys/linea-attestation-registry/blob/5863e8848e4e2d70003e74d84cf17ca07cfd90f3/sdk/src/dataMapper/UtilsDataMapper.ts#L34) to rely on the subgraph instead of the contract
